name 'elasticsearch_practice'
maintainer 'Annie Hedgpeth '
maintainer_email 'annie.hedgpeth@gmail.com'
license 'all_rights'
description 'Installs/Configures elasticsearch_practice'
long_description 'Installs/Configures elasticsearch_practice'
version '0.1.0'
